### ISSUE TITLE
Directory resolution

### ISSUE THREAD

**Issue by robross0606** [mateussouzaweb/vscode-notes-box#2]
I really love what this extension can do, short of one small feature.  The extension seems to be heavily geared towards Unix shell where `~` means something so you can do `~/Notes/` as in the example for save directory.  However, this doesn't work in Windows.  Now that settings can be saved to the cloud and mirrored across installations of VSCode, it has become impossible for me to have settings for this extension that work across all my usages of VSCode with this extension.  Recommend either finding a more OS-neutral means of specifying a consistent directory path, or having separate settings for different OS.  I've seen other extensions do it this way for Windows, MacOS and Linux, though MacOS and Linux could arguably be handled as one.

**Comment by mateussouzaweb** [comment]
This feature already has been implemented in the extension - 9c7eea3
